version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=restaurant_manager
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - psql-data:/var/lib/postgresql/data
    ports:
      - "5432"
  web:
    build: .
    tty: true
    stdin_open: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  psql-data:
    driver: local