# Generated by Django 3.1.5 on 2021-01-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210120_1228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'restaurant')},
        ),
    ]
