# Generated by Django 3.1.5 on 2021-01-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210124_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='menuitemtype',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk'], 'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'restaurant')},
        ),
    ]
